import Head from 'next/head'
import Main from '../src/components/main'
import Footer from '../src/components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Consultador de CEP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Main/>
      <Footer/>
    </>
  )
}
